# Generated by Django 4.2 on 2025-09-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('shortlisted', 'Shortlisted Top5'), ('interview_scheduled', 'Interview Scheduled'), ('interview_done', 'Interview Done')], default='applied', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_extracted_data', models.JSONField(blank=True, help_text='AI-extracted structured data from latest CV', null=True)),
                ('ai_extraction_date', models.DateTimeField(blank=True, help_text='When the AI extraction was last performed', null=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated candidate summary')),
                ('ai_score_out_of_10', models.DecimalField(blank=True, decimal_places=1, help_text='AI score for latest vacancy application', max_digits=4, null=True)),
                ('ai_analysis', models.TextField(blank=True, help_text='AI analysis of the candidate for latest vacancy')),
                ('ai_score_breakdown', models.JSONField(blank=True, help_text='Detailed AI scoring breakdown', null=True)),
                ('ai_scoring_date', models.DateTimeField(blank=True, help_text='When the AI scoring was last performed', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='candidates.application')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_file', models.FileField(blank=True, help_text='CV file (PDF, DOC, DOCX, TXT)', null=True, upload_to='cvs/')),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text from CV file for AI processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='AI-generated candidate summary')),
                ('skills_analysis', models.JSONField(help_text='Detailed skills analysis')),
                ('experience_level', models.CharField(help_text='Experience level assessment', max_length=50)),
                ('strengths', models.JSONField(help_text='Key strengths identified')),
                ('areas_for_improvement', models.JSONField(help_text='Areas for improvement')),
                ('cultural_fit_score', models.DecimalField(decimal_places=1, help_text='Cultural fit score 1-10', max_digits=4)),
                ('technical_score', models.DecimalField(decimal_places=1, help_text='Technical skills score 1-10', max_digits=4)),
                ('overall_recommendation', models.TextField(help_text='Overall AI recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='candidates.candidate')),
            ],
        ),
    ]
