# Generated by Django 4.2 on 2025-09-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='latest_vacancy_scored',
            field=models.ForeignKey(blank=True, help_text='Latest vacancy this candidate was scored against', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.vacancy'),
        ),
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.cv'),
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('vacancy', 'cv')},
        ),
    ]
