# Generated by Django 4.2 on 2025-10-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated candidate summary', null=True),
        ),
    ]
