# Generated by Django 4.2 on 2025-10-21 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
        ('candidates', '0003_alter_candidate_ai_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateVacancyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(blank=True, help_text='Current application status', max_length=30)),
                ('application_date', models.DateTimeField(blank=True, help_text='When candidate applied', null=True)),
                ('cv_file_name', models.CharField(blank=True, help_text='Name of the CV file uploaded', max_length=255)),
                ('ai_extracted_data', models.JSONField(blank=True, help_text='AI-extracted structured data from CV', null=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=1, help_text='AI score for this vacancy', max_digits=4, null=True)),
                ('ai_analysis', models.TextField(blank=True, help_text='AI analysis for this specific vacancy')),
                ('ai_score_breakdown', models.JSONField(blank=True, help_text='Detailed AI scoring breakdown', null=True)),
                ('ai_analysis_date', models.DateTimeField(blank=True, help_text='When AI analysis was performed', null=True)),
                ('manager_feedback', models.TextField(blank=True, help_text='Manager feedback from interview (full email body)')),
                ('manager_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='Manager rating of the candidate', null=True)),
                ('manager_recommendation', models.BooleanField(blank=True, help_text='Whether manager recommends this candidate', null=True)),
                ('feedback_received_date', models.DateTimeField(blank=True, help_text='When manager feedback was received', null=True)),
                ('interview_scheduled', models.BooleanField(default=False, help_text='Whether interview was scheduled')),
                ('interview_date', models.DateTimeField(blank=True, help_text='Interview date and time', null=True)),
                ('interview_duration', models.IntegerField(blank=True, help_text='Interview duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_profiles', to='candidates.candidate')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Candidate Vacancy Profile',
                'verbose_name_plural': 'Candidate Vacancy Profiles',
                'ordering': ['-created_at'],
                'unique_together': {('candidate', 'vacancy')},
            },
        ),
    ]
