# Generated by Django 4.2 on 2025-10-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidatevacancyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatevacancyprofile',
            name='questionnaire_response',
            field=models.TextField(blank=True, help_text='Candidate questionnaire response (full email body)'),
        ),
        migrations.AddField(
            model_name='candidatevacancyprofile',
            name='questionnaire_response_date',
            field=models.DateTimeField(blank=True, help_text='When questionnaire response was received', null=True),
        ),
    ]
