# Generated by Django 4.2 on 2025-11-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidatevacancyprofile_questionnaire_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatevacancyprofile',
            name='recommendation_email_sent',
            field=models.BooleanField(default=False, help_text='Whether hiring recommendation email has been sent'),
        ),
        migrations.AddField(
            model_name='candidatevacancyprofile',
            name='recommendation_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When hiring recommendation email was sent', null=True),
        ),
    ]
