# Generated by Django 4.2 on 2025-09-30 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0002_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('manager_notified', models.BooleanField(default=False)),
                ('candidate_notified', models.BooleanField(default=False)),
                ('manager_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_request_sent', models.BooleanField(default=False)),
                ('feedback_request_sent_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Video call link if applicable')),
                ('notes', models.TextField(blank=True, help_text='Interview notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.candidate')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to='vacancies.vacancy')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.IntegerField(help_text='Technical skills rating (1-10)')),
                ('communication', models.IntegerField(help_text='Communication skills rating (1-10)')),
                ('problem_solving', models.IntegerField(help_text='Problem solving rating (1-10)')),
                ('cultural_fit', models.IntegerField(help_text='Cultural fit rating (1-10)')),
                ('overall_rating', models.IntegerField(help_text='Overall rating (1-10)')),
                ('strengths', models.TextField(help_text='Candidate strengths')),
                ('areas_for_improvement', models.TextField(help_text='Areas for improvement')),
                ('additional_notes', models.TextField(blank=True, help_text='Additional notes')),
                ('recommendation', models.CharField(choices=[('hire', 'Hire'), ('no_hire', 'No Hire'), ('maybe', 'Maybe'), ('strong_hire', 'Strong Hire')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interviews.interview')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interviews.interviewslot'),
        ),
        migrations.AddField(
            model_name='interview',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='vacancies.vacancy'),
        ),
        migrations.CreateModel(
            name='CalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(help_text='Zoho Calendar ID', max_length=200)),
                ('calendar_uid', models.CharField(help_text='Zoho Calendar UID', max_length=200)),
                ('caldav_url', models.URLField(help_text='CalDAV URL for calendar access')),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token expiration time', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='UTC', help_text='Manager timezone', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_integration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('vacancy', 'candidate')},
        ),
    ]
