# Generated by Django 4.2 on 2025-10-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarintegration',
            name='caldav_password',
            field=models.CharField(blank=True, default='', help_text='CalDAV basic auth password', max_length=255),
        ),
        migrations.AddField(
            model_name='calendarintegration',
            name='caldav_username',
            field=models.CharField(blank=True, default='', help_text='CalDAV basic auth username', max_length=255),
        ),
    ]
