# Generated by Django 4.2 on 2025-10-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_calendarintegration_caldav_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(help_text='Manager feedback on the interview')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='Manager rating of the candidate', null=True)),
                ('recommended', models.BooleanField(blank=True, help_text='Wether manager recommends this candidate', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_feedback', to='interviews.interview')),
            ],
            options={
                'verbose_name': 'Manager Feedback',
                'verbose_name_plural': 'Manager Feedback',
            },
        ),
    ]
