# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_managerfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_slot',
            field=models.ForeignKey(
                blank=True,
                help_text='Set when interview is scheduled and emails sent',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='interviews',
                to='interviews.interviewslot',
            ),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Set when interview is scheduled and emails sent',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending_approval', 'Pending Approval'),
                    ('scheduled', 'Scheduled'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                    ('rescheduled', 'Rescheduled'),
                ],
                default='pending_approval',
                max_length=20,
            ),
        ),
    ]
