# Generated by Django 4.2 on 2025-09-30 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('collecting_applications', 'Collecting Applications'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='awaiting_approval', max_length=30)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for CV scoring')),
                ('require_dob_in_cv', models.BooleanField(default=True)),
                ('require_egyptian', models.BooleanField(default=False)),
                ('require_relevant_university', models.BooleanField(default=False)),
                ('require_relevant_major', models.BooleanField(default=False)),
                ('questionnaire_template', models.TextField(blank=True, help_text='Plain JSON or newline questions')),
                ('meta', models.JSONField(blank=True, help_text='Additional metadata like approval tokens', null=True)),
                ('linkedin_posted_at', models.DateTimeField(blank=True, help_text='When posted on LinkedIn', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn job posting URL')),
                ('collection_ends_at', models.DateTimeField(blank=True, help_text='When to stop collecting applications', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vacancies', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_vacancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='Rank in shortlist (1-5)')),
                ('ai_score', models.DecimalField(decimal_places=1, help_text='AI score out of 10', max_digits=3)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this candidate')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_entries', to='candidates.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='candidates.candidate')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='vacancies.vacancy')),
            ],
            options={
                'ordering': ['vacancy', 'rank'],
                'unique_together': {('vacancy', 'rank')},
            },
        ),
    ]
